import Vue from 'vue';
import {Col,Row,Menu,MenuItem,MenuItemGroup,Tree,Submenu} from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';

Vue.use(Tree);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(MenuItemGroup);
Vue.use(Submenu);
Vue.use(Row);
Vue.use(Col);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(Submenu);
// Vue.use(ElementUI);